language: csharp
mono: none
dotnet: 3.1.100
solution: JG.TechLearning.CarDiagnosticApp.sln
stages:
  - build
jobs:
  include:
    - stage: build
      name: build solution
      script: dotnet restore && dotnet build
